kubernetes-sigs/kpng

hack/README.md, hack/kpng-deployment-ds.yaml.tmpl, hack/kpng-local-up.sh
iterating, this gets us over the apiserver hump....
=> fix the kpng kube-proxy connectivity by mounting the kubelet host

backends/ipvs/flags.go, backends/ipvs/ipvs.go, backends/ipvs/prerun.go, cmd/kpng-ipvs-backend/kpng-ipvs-backend.go, go.mod, go.sum
Signed-off-by: Ricardo Pchevuzinske Katz <ricardo.katz@gmail.com>
As we spoke this week, moving my non suitable for Prod (or for demos, or anything) hacky ipvs implementation to main repo :)
=> Move ipvs impl to main repo

hack/README.md, hack/kpng-deployment-ds.yaml.tmpl, hack/kpng-local-up.sh
update local instructions to support pull policy, loading kind images locally rather then dockerhub
=> Kpng local ipvs

backends/nft/nft.go, hack/kpng-deployment-ds.yaml.tmpl
This is fix for issue #26 
Other minor fix is a spelling mistake in deployment yaml file
=> Added code in NFT backend to check for iptable version

jobs/kube2store/kube2store.go
This PR is for fixing the below failing test cases :
- [Fail] [sig-network] Services [It] should implement service.kubernetes.io/service-proxy-name
- [Fail] [sig-network] Services [It] should implement service.kubernetes.io/headless
=> Fix headless and service proxy name tc's

.github/workflows/backend-build.yml, hack/build.sh
=> github actions for backend builds

hack/resolve_all_mod_files.sh, hack/test_unit.sh
Adds the script `test_unit` that resolves all `mod.go` files and triggers all `*test.go` tests. This also serves as a starting point for gh actions. 
To run just: 
```./hack/test_unit.sh```
This is what you are supposed to see:
```➜  kpng git:(test_unit.sh) ./hack/test_unit.sh
==================================
resolving mod files
==================================
downloading mods in ./api
downloading mods in ./examples/iptables-extip
downloading mods in ./examples/pipe-exec
downloading mods in ./examples/print-state
downloading mods in ./examples/userspace-proxier
downloading mods in ./server
downloading mods in ./client
downloading mods in ./backends/iptables
downloading mods in ./backends/ipvs-as-sink
downloading mods in ./backends/nft
downloading mods in ./cmd …
```
=> adding test_unit.sh to run all unit tests

.github/workflows/build_test_unit.yml
=> add GH actions for unit tests build

hack/.gitignore, hack/kpng-local-up.sh, hack/setup_sonobuoy.sh, hack/test_sonobuoy.sh
First iteration of sonobuoy tests. Just run ``` ./hack/test_sonobuoy.sh ``` It should set up the whole test env and run the sonobuoy quick test. 
In future iterations, we could add more tests and run them via GH Actions.
=> adding conformance tests

.github/workflows/test_sonobuoy.yml, hack/setup_sonobuoy.sh
=> test sonobuoy GH action

hack/kpng-local-up.sh
hack/kpng-local-up.sh is breaking due a not existent function, removing it.
=> Removing not existent cni_config function

backends/iptables/service.go
Changes for supporting LoadBalancer service in iptables mode.
=> LoadBalancer support

.github/OWNERS, hack/OWNERS
=> add owners and approvers for ci

hack/test_e2e.sh
=> fixed kubeconfig issue

hack/test_e2e.sh
=> fix kubeconfig 2

backends/iptables/iptables.go, backends/iptables/service.go, backends/iptables/types.go
This PR contains following :
1)Changes for breaking down the sync() function(syncProxyRules() in upstream) for better readability and creating few functions for code reuse.
2)Support for session affinity in the iptables backend
=> iptable backend changes for better readability and session affinity support

hack/test_e2e.sh
Developers might not use only docker but different
containers engine like podman. This patch adds support to it.
=> test_e2e: Add container engine validation

hack/kpng-deployment-ds.yaml.tmpl, hack/test_e2e.sh
- e2e: use kubectl --all-namespaces
- e2e: specify image registry for kindest/node
- e2e: replace --timeout to --request-timeout
- e2e: show error if kind cannot load image
- e2e: fail if kind create cluster fails
=> e2e: improvements

server/pkg/proxystore/proxystore_test.go
Creates a unit test to SessionAffinity
GitHub-Issue: https://github.com/kubernetes-sigs/kpng/issues/156
Signed-off-by: Jay Vyas (jayunit100) <jvyas@vmware.com>
=> proxystore_test: Add unit test to SessionAffinity

backends/ipvs-as-sink/clusteripsvc.go, backends/ipvs-as-sink/common.go, backends/ipvs-as-sink/flags.go, backends/ipvs-as-sink/helpers.go, backends/ipvs-as-sink/ipset.go, backends/ipvs-as-sink/iptables.go, backends/ipvs-as-sink/ipvs.go, backends/ipvs-as-sink/loadbalancersvc.go, backends/ipvs-as-sink/nodeportsvc.go, backends/ipvs-as-sink/proxier.go
IPVS  backend iptable implementation.
Added iptable implementation using reference count based approach (#164).
=> ipvs iptable implementation

README.md
change cillium to cilium.
Signed-off-by: Kay Yan <kay.yan@daocloud.io>
=> FIx small typo in readme.md

hack/kpng-local-up.sh
refactory of test_e2e added more env vars
to the template file which kpng-local-up was not aware.
This patch fix this issue.
=> kpng-local-up: add missing env vars

README.md
Github-Issue: https://github.com/kubernetes-sigs/kpng/issues/181
=> README: add APAC meeting details

Makefile
makefiles helps users in the learn curve and maintenance.
=> build: Add initial Makefile

backends/iptables/endpoints.go, backends/iptables/endpointsCache.go
The code has the type, let's make use of it.
=> iptables: use the type EndpointsMap

hack/test_e2e.sh
I updated the test_e2e to make less assumptions, it is now possible to: 
specify where the e2e files will be stored
specify which Dockerfile to use
run the command from anywhere, just not from the kpng directory
No assumptions regarding that /usr/local/bin exist, or is part of the $PATH
=> Make hack/test_e2e assume less about environment around it

hack/OWNERS
I have been involved in scripts behind hack/ dir.
If possible, please add me as reviewer and commiter.
=> hack: add dougsland to OWNERS

hack/README.md
- hack: README - add note about joining kind node
- hack: README - add conntrack notes
=> More documentation about development

backends/iptables/endpoints.go
Use some friendly name for more compressive understanding
of the code.
Example, now we can use:
- service.Name
- service.Namespace
- endpointEntry.IPs.V4
- endpointEntry.IPs.V6
=> backend/iptables: rename vars

CONTRIBUTING.md
quick contributing.md based on https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/CONTRIBUTING.md#notes-on-minutiae
=> Add contributing w/ notes on minutia

backends/ipvs-as-sink/clusteripsvc.go, backends/ipvs-as-sink/common.go, backends/ipvs-as-sink/externalIP.go, backends/ipvs-as-sink/ipvslb.go, backends/ipvs-as-sink/loadbalancersvc.go, backends/ipvs-as-sink/nodeportsvc.go
added session affinity code for clusterIP , externalIP, loadbalancer IP, node port IPs.
=> adding session affinity code in ipvs

OWNERS
=> adding myself, vivek root owners

backends/windows/userspace/backend.go, backends/windows/userspace/loadbalancer.go, backends/windows/userspace/main.go, backends/windows/userspace/proxier.go, backends/windows/userspace/proxysocket.go, backends/windows/userspace/roundrobin.go, backends/windows/userspace/utils.go
Fixing a few issues on windows userspace backend:
1. go fmt
2. Protocol string instead of converting protobuf manually on svc build
3. Using targetPort instead of svcport on helper data strcuture
=> Fixing targetport and adding klog flags

hack/test_e2e.sh
Included some upstream updates from e2e tests
Added small description regarding "not-kpng"
=> e2e_test: Made kind ipv6 core dns patch default when using IPv6

client/serviceevents/service-events.go, client/serviceevents/service-events_test.go
It fixes compilation issue , as well as need to passing previous service obj while disabling session affinity
#247
=> Fixing compilation issue

backends/ipvs-as-sink/baseportinfo.go, backends/ipvs-as-sink/clusteripsvc.go, backends/ipvs-as-sink/common.go, backends/ipvs-as-sink/exec/exec.go, backends/ipvs-as-sink/externalIP.go, backends/ipvs-as-sink/ipset.go, backends/ipvs-as-sink/iptables.go, backends/ipvs-as-sink/ipvs.go, backends/ipvs-as-sink/ipvslb.go, backends/ipvs-as-sink/loadbalancersvc.go, backends/ipvs-as-sink/nodeportsvc.go, backends/ipvs-as-sink/proxier.go, backends/ipvs-as-sink/util/ipset.go, backends/ipvs-as-sink/util/iptables.go, backends/ipvs-as-sink/util/iptables_linux.go, backends/ipvs-as-sink/util/save_restore.go, backends/ipvs-as-sink/util/utils.go, client/serviceevents/service-events.go, hack/kpng-deployment-ds.yaml.tmpl
Handling of service updates in IPVS for session affinity etc.
=> Code changes to handle service updates

client/plugins/conntrack/conntrack.go, client/plugins/conntrack/conntrack_test.go
@qabpea first thing first, a basic conntrack test
=> conntrack: basic Example test

server/pkg/server/watchstate/watchstate.go
=> watchstate: allow multiple stores per set

hack/test_e2e.sh
@uablrek I think it will impact #313 significantly.
=> test e2e: improve IPv6 handling and bump versions

hack/test_e2e.sh
Signed-off-by: Brent Salisbury <bsalisbu@redhat.com>
=> Bumped e2e CI to k8s latest release

hack/test_e2e.sh
cleaned up installation of bpf2go and j2, repaired printout of test results to work with new output from k8s e2e tests
=> cleanup and repair of test_e2e.sh 

server/doc.go
@astoycos some doc to help
Depends (softly) on #363 for the proxystore's links.
=> server: add some doc with pointers to each function of the server

.github/workflows/backend-build.yml, .github/workflows/e2e_tests.yaml, hack/test_backend_build.sh
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
=> add userspace to ci

backends/OWNERS
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
=> add aryan9600 to backends/OWNERS

.github/workflows/backend-build.yml, .github/workflows/e2e_tests.yaml, .github/workflows/unit_tests.yml
=> bump go version in CI to 1.19

OWNERS, backends/OWNERS
So that I can review and approve fixes to userspace backend
=> Add rajas to OWNERS

backends/userspacelin/roundrobin.go, backends/userspacelin/sink.go, backends/userspacelin/userspace_util.go
* fix endpoints deletion handling in userspace: fixes https://github.com/kubernetes/kubernetes/blob/fbb6ccc0c62d2431dc3a18a4130d7fbae5c05acd/test/e2e/network/service.go#L792
* fix port to endpoint mapping in userspace: fixes  https://github.com/kubernetes/kubernetes/blob/fbb6ccc0c62d2431dc3a18a4130d7fbae5c05acd/test/e2e/network/service.go#L792
=> Improve userspace backend 

backends/nft/nft.go
Signed-off-by: Anil Kumar Vishnoi <vishnoianil@gmail.com>
=> Fix minor typos

CONTRIBUTING.md, README.md
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
=> improve CONTRIBUTING.md

cmd/kpng/a2s.go, cmd/kpng/f2s.go, cmd/kpng/k2s.go, cmd/kpng/storecmds/command_builder.go, hack/common.sh, hack/kind.yaml, hack/kpng-local-up.sh
Was missing the lambda internalization from last commit , second half of #411 , fixes the first half of #416
=> Finish adding lambdas explicitly and also fix some kpng-local-up.sh errors related to legacy mode

client/client.go, client/localsink/fullstate/fullstate.go, client/localsink/fullstate/fullstatepipe/fullstatepipe.go, server/pkg/proxy/server.go
cleanup some cases of useless buffering for chans.
=> chore: remove buffers on some chans

doc/service-proxy.md
- link to end-user service/proxy docs
- fix reference to userspace proxy, which no longer exists upstream
- rewrite some stuff where I was trying to pluralize field names in a way that looks bad in the rendered doc
- update recommendations around localhost nodeports ("don't!")
- assume ProxyTerminatingEndpoints (since it's expected to be GA in 1.27), and describe it as applying to all services, not just eTP:Local ones (cf https://github.com/kubernetes/kubernetes/pull/108691)
- fix definition of "internal" vs "external" connections to be destination-based, not source-based (cf https://github.com/kubernetes/kubernetes/issues/108526)
- explain _why_ eTP:Local drops bad traffic rather than rejecting it
- rewrite "Port Listeners" section to describe it as something we _used to_ do rather than …
=> misc service-proxy.md updates

.github/workflows/local-up-kpng.yaml
Created a Github Action workflow - local-up-kpng.yaml - for local-up-kpng.sh. 
Solves #420
=> Ci job smoke test #420

.github/workflows/backend-build.yml, .github/workflows/e2e_tests.yaml, .gitignore, Makefile, hack/test_skip_list.sh
This PR enables CI tests for IPVS Fullstate backend.
=> CI for ipvsfullstate

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Fixes #486 by adding Pull requests and issue templates in the .github
=> Adds issue and pull request templates.

Makefile, hack/tilt/README.md, hack/tilt/Tiltfile
Bug and Documentation
The PR consist of the readme for ruuning titl on kpng, and a minor fix on makefile and tiltfile
Fixes #490
N/A
=> Added readme to the tilt tutorial and fix some makefile bug

.github/workflows/backend-build.yml, .github/workflows/docker-action.yml, .github/workflows/e2e_tests.yaml, .github/workflows/local-up-kpng.yaml, .github/workflows/unit_tests.yml, .github/workflows/vet-code.yml
fix deprecations in github actions
=> Chore gh actions

.github/workflows/e2e_tests.yaml
bumping a few more deprecations
=> gh actions: upgrade deprecated checkout action

Dockerfile, api/go.mod, backends/ebpf/go.mod, backends/healthchecks/go.mod, backends/iptables/go.mod, backends/ipvs/go.mod, backends/nft/go.mod, backends/userspacelin/go.mod, backends/windows/kernelspace/go.mod, backends/windows/userspace/go.mod, client/go.mod, cmd/go.mod, examples/iptables-extip/go.mod, examples/pipe-exec/go.mod, examples/print-state/go.mod, examples/userspace-proxier/go.mod, server/go.mod
=> bump go to 1.20

hack/common.sh, hack/test_e2e.sh, hack/test_skip_list.sh
updating tests to us K8s version 1.27.1 and kind version to 0.18
=> update to use k8s 1.27.1 and kind 0.18

hack/metrics/grafana-dashboards/kpng.json
```
cd hack
DEPLOY_PROMETHEUS=true ./kpng-local-up.sh
```
go to http://chart-example.local/dashboards , find the kpng dashboard!
=> first grafana dashboard

.github/workflows/e2e_tests.yaml, hack/test_skip_list.sh
=> IPVS CI fix for k/k v1.26.0+

client/client.go, client/localsink/fullstate/fullstate.go, client/run.go, cmd/kpng-globallog/main.go
Improvement
See https://github.com/kubernetes-sigs/kpng/issues/484#issuecomment-1522807182. The PR renames the `EndpointsClient` to `LocalClient` as per the suggested comment
Fixes #484
=> rename EndpointsClient to LocalClient

hack/test_e2e.sh
This PR adds sha to image tag in E2E_K8S_version
Fixes # 510
=> Add SHA to image tag

OWNERS
=> github user-name changed

backends/nft/nft.go, backends/nft/render-context.go, backends/nft/render-context_test.go
It may solve some issues, let's see what the tests will say.
=> nft: dispatch per IP+port, not just IP
