kubernetes-sigs/kpng

backends/nft/nft.go
pkg/api/localnetv1/ipset.go

The `net.To4` could convert an IPv6 address to an IPv4 address.
Using `To4` could cause IPv6 addresses wrongly classified as IPv4 ones.
More details in https://github.com/golang/go/blob/189c6946f598dc668946499e4179775c06295f9d/src/net/ip.go#L209-L222
Signed-off-by: Hanlin Shi <shihanlin9@gmail.com>

Fix ipfamily classification

---

hack/kpng-local-up.sh

Currently in kind project there is no master branch, there is main.
This patch updates the code to the new branch and also use
export command to replace chmod/cp which are not needed.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

kpng-local-up: use main instead of master

---

backends/ipvs-as-sink/flags.go
backends/ipvs-as-sink/helpers.go
backends/ipvs-as-sink/ipvs.go
backends/ipvs-as-sink/lb.go

Other changes:
* Made scheduling method and weight as configurable param
* Fixes related to Service Update in IPVS backend
a) whenever service is updated with new portMapping(port,
protocol,targetPort) , EP will be added under new IPVS LB IP
b) whenever service is update where a portMapping is removed, EP entry
related to that protocol/port will be deleted.

Adding NodePort service support for IPVS backend

---

backends/ipvs-as-sink/clusteripsvc.go
backends/ipvs-as-sink/common.go
backends/ipvs-as-sink/flags.go
backends/ipvs-as-sink/helpers.go
backends/ipvs-as-sink/ipset.go
backends/ipvs-as-sink/ipvs.go
backends/ipvs-as-sink/lb.go
backends/ipvs-as-sink/nodeportsvc.go
backends/util/ipvs/ipset.go
backends/util/ipvs/types.go

This PR contains following code changes
a) ClusterIP , NodePort related IPSet are added.
KUBE-LOOP-BACK
KUBE-6-LOOP-BACK
KUBE-CLUSTER-IP
KUBE-6-CLUSTER-IP
KUBE-NODE-PORT-TCP
KUBE-6-NODE-PORT-TCP
KUBE-NODE-PORT-UDP
KUBE-6-NODE-PORT-UDP
Other IPSets will be added in subsequent review
b) Dual stack handling for service and endpoints

ClusterIP and NodePort service IPSet entries added

---

hack/build.sh

I changed the logic in `build.sh` so new backend packages would automatically also be tested and if 'old' backends get removed nothing breaks. On purpose, this only changes the code that is NOT used by GH actions.
I also added the license boilerplate text.

more generic build.sh

---

client/serviceevents/service-events.go

When port is deleted from service , the service event handling code used to crash due to wrong index check.

Fixing service event handling

---

backends/iptables/iptables.go
backends/iptables/util/iptables_save_restore.go
backends/iptables/util/utils.go

1) porting latest optimization from kube-proxy
https://github.com/kubernetes/kubernetes/pull/106158
2) Moving common file to iptables/util , so that even ipvs backend can use the common functions.

porting iptable changes from kube-proxy

---

hack/test_e2e.sh

If docker command failed in the kpng docker image function
the ./test_e2e.sh should stop.

test_e2e: validate if docker cmd failed

---

hack/test_e2e.sh

test_e2e is nice tool to create kpng enviroment.
However, it always run e2e tests (as expected) which
consumes a bunch of time. This patch adds -d to skip e2e
and allow fast env creation for developers.

test_e2e: create -d for development mode

---

hack/e2e_export_logs.sh

WARNING: --loglevel is deprecated, please switch to -v and -q!

e2e_export_logs: remove warning message

---

backends/ipvs-as-sink/ipvs.go

Before using ip, assure it exists.

ipvs: validate net.ParseCIDR

---

api/localnetv1/ipset.go

No need to have twice the code to generate double
maintenance.

ipset: avoid dup code for diffstrings

---

backends/iptables/iptables.go

Setting the default value to false.
A default value of true implied that all requests are snat-d which
prevented from preserving the source ip even for traffic from within the
cluster.
Fixes #162

Default value for masqueradeAll flag for iptables

---

go-mod-tidy-all

Check if go bin exists and if it's the version
that introduced -compat for go mod tidy.

go-mod-tidy-all: add validations

---

hack/kpng-local-up.sh

essential MR to fix the fact that kpng-local-up fails silently ... 
fixes #212

fail kpng local up if compilation is broken

---

client/serviceevents/service-events.go

In below DeleteIPPort API, svc object carries incorrect info.
`DeleteIPPort(svc *localnetv1.Service, ip string, ipKind IPKind, port *localnetv1.PortMapping)`
Lets see the following sequence of events:
a) Create service-A with port-A. So the svc object, will have port-A info.
b) Create endpoint
c) Update service-A with port-B. So the svc object, will have port-B info in addition to port-A.
d) Remove port-B and update service-A. Now `DeleteIPPort` is invoked with svc object having both port-A,port-B. 
Anyway the deleted port i.e port-B is passed as parameter.
Backends storing svc object will get into trouble especially during EP addition/deletion.
Backends end up reading stale svc object with incorrect info.
Other options for backend is that , they need to store port info rather than …

Fixing DeleteIPPort API with currentSvc object

---

backends/iptables/iptables.go

This fixes iptables backend panic while programming iptable rules for external IP when there are no endpoints .

Fix external ip panic on no endpoints

---

server/jobs/kube2store/service-event-handler.go

`svc.Spec.InternalTrafficPolicy` is a pointer in comparison to `svc.Spec.ExternalTrafficPolicy` . So it could be null.

fix for kpng server crash

---

backends/ipvs-as-sink/ipvs.go
client/serviceevents/service-events.go
client/serviceevents/service-events_test.go
client/serviceevents/traffic_policy_kind.go
client/serviceevents/wrap.go

This code change enhances `client/serviceevents/service-events.go` to provide API's for `TrafficPolicy(Internal/External)` and `sessionAffinity`. IPVS currently uses filter reset + service events.
IPVS Backend code handling these events will be raised in subsequent patch.
#215 
Mikael's suggestion is to use fullstate + diffstore for IPVS. We will explore this option as well, if performance numbers for above design are pathetic .

Enhancing service events for traffic policy and session affinity

---

server/jobs/kube2store/slice-event-handler.go

Fixes #241 
Instead of choosing only the last port, we need to assign all `port names: numbers` to the endpoint port map.

EndpointPortMap update fix

---

hack/test_e2e.sh

Added code that verify the host network settings and also code that set them if ci/cd is set.
Made delete of clusters used for test default behaviour
Small changes in ginko settings in test_run
Prepared for changes in how kind cluster is created

test_e2e: fix to make ipv6 tests run correctly (or detect incompatible sysctl settings)

---

backends/iptables/sink.go
client/localsink/filterreset/pipe/sink.go
client/plugins/conntrack/conntrack_linux.go
client/plugins/conntrack/sink.go

Currently stale conntrack entries for iptables are not handled and hence conntrack related test cases are failing.
Fixes: #261

Pipe for filterreset and stale conntrack handling for iptable

---

backends/ipvs-as-sink/go.mod
backends/ipvs-as-sink/ipvs.go

E2E testcases for session affinity check for the type of backend i.e ipvs or iptable. This check is to decide the expiry time of session affinity. For IPVS , the minimum time is 120sec.

Implementing http endpoint to query the backend

---

backends/nft/nft.go
backends/nft/render-context_test.go
hack/kpng-deployment-ds.yaml.tmpl
hack/kpng-local-up.sh
hack/test_e2e.sh

This should fix the persistent test flakes observed in the following e2e tests (when run against the nft backend):
* `should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance] `
* `should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] `
* `should have session affinity work for NodePort service [LinuxOnly] [Conformance] `
Changes include:
* Preventing the masquerading of local traffic directly within the host
* Configuring the correct `CLUSTER_CIDR` values so that the *rest of the values* are masqueraded.

Fix masquerading in NFT backend

---

hack/test_e2e.sh

Remove the duplicate function delete_kind_cluster in e2e-test.sh
Signed-off-by: Brent Salisbury <bsalisbu@redhat.com>

Remove duplicate function in e2e-test.sh

---

go.work
hack/go-build

The `examples/` items should be included in `go.work`, else they can't be built.
Also use $VERSION in binaries. I not set the version defaults to the output from;
```
git describe --dirty --tags
```
I myself becomed very annoyed if I can't get the version of programs I am using and I assume I am not alone.

Include example in go.work

---

backends/ebpf/README.md

eBPF backend needs this lib to compile the eBPF objects.
In absence of this library `go generate` will throw following error
`/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not
found`
Signed-off-by: Anil Kumar Vishnoi <vishnoianil@gmail.com>

Add gcc-multilib as dependency

---

backends/windows/kernelspace/endpoints.go

Remove this reference so that we
don't get deprocation warnings.
It's only used for
```
string(discovery.AddressTypeIPv4),
string(discovery.AddressTypeIPv6),
```
Which is an type still included in
v1 of the API.
Should fix #339

Remove reference to endpoint's type

---

.github/workflows/backend-build.yml
.github/workflows/e2e_tests.yaml
.github/workflows/unit_tests.yml
backends/ipvs-as-sink/ipvs.go
hack/kpng-local-up.sh
hack/test_e2e.sh
hack/utils.sh

While trying to run the project locally using `hack/kpng-local-up.sh`, I encountered several problems:
* Using the ipvs backend used to cause a panic, because the base distro being used in the kind node was out of date hence there was no `proc/sys/net/ipv4/vs` present, resulting in `Setup()` to fail silently. Later when a new service gets synced, `AddIP()` panics because `s.dummy` never got set.
* The `hack/kpng-local-up.sh` is out of date using `envsubst` instead of `j2`

Update kpng-local-up.sh and fix potential IPVS panic

---

hack/README.md

This PR fixes the documentation on the Run from source section which repeats the env var IMAGE with the invalid reference format and also fixes the path to run the `kpng-local-up.sh` script

Fix hack README.md run from source

---

backends/userspacelin/sink.go
backends/userspacelin/userspace_util.go

* Remove log statement referencing a service's ClusterIP(s) while syncing headless services
* Increase UDP connection timeout fixing DNS resolution issues.
Fixes: #335
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>

fix userspace panic while syncing headless svc and dns resolution

---

hack/kpng-local-up.sh

This PR has a small fix to kpng-local-up.sh so it can be run from the source root without issues importing the utils.sh

Fix to run kpng-local-up.sh from source root

---

doc/service-proxy.md

Clarifies that setting allocateNodePorts=false to a load balancer service has nothing to do with the healthcheckNodePorts.
/cc @danwinship PTAL

Add info about allocateNodePorts=false to the service-proxy docs

---

hack/test_e2e.sh

hack/test_e2e.sh#L641 uses **info_message** function to persist cluster name to file, which adds _ANSI color escape sequences and INFO label_ along with cluster name.
On disk clustername becomes **[ \x1b[34mINFO\x1b[0m ] kpng-e2e-ipv4-iptables** instead of **kpng-e2e-ipv4-iptables**
Using **echo** to persist cluster name instead of **info_message**

using echo instead of info_message to persist cluster_name

---

hack/test_e2e.sh

Problem
Setting erase_clusters=false in ./hack/test_e2e.sh erases cluster.
Solution
Adding erase_clusters at the end of **main** function in **test_e2e.sh**
this probably fixes #352

added erase_cluster check before delete_kind_clusters call

---

cmd/kpng/a2s.go
cmd/kpng/builder/command_builder.go
cmd/kpng/f2s.go
cmd/kpng/k2s.go
cmd/kpng/local.go
cmd/kpng/main.go

Moving `command_builder` to a `builder` module in order to be able to use `ToLocalCmd` or `LocalCmds` on external projects.
https://github.com/kubernetes-sigs/windows-service-proxy/pull/1
Adding the backends Register in the main.go instead, so the modules listed on `storecmds` are NOT imported automatically when `builder` is used.

Moving command_builder to builder module

---

.github/workflows/security.yaml

fixes #424 
This PR introduces a simple security pipeline.
It uses [gosec](https://github.com/securego/gosec) and [govulncheck](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) (static code analysis tools) to scan for common/known vulnerabilities.
Both tools upload SARIF reports that are later used by the [Github's code scanning API](https://docs.github.com/en/rest/code-scanning?apiVersion=2022-11-28).
Signed-off-by: jaehnri <joao.henri.cr@gmail.com>

add security pipeline that scans with gosec and govulncheck

---

.github/workflows/security.yaml

Signed-off-by: João Henri <joao.henri.cr@gmail.com>
There are currently a couple of rules picking annoying false positives. `gosec` is identifying some constants as credentials and complaining for every file inclusion done by variable.

Ignore gosec false positives

---

hack/test_e2e.sh
hack/utils.sh

- move all 'source'ing to the beginning. Fixes the issue of 'info_message' being not available since `utils.sh` is not sourced at the point it's used
- change control sequence for terminal colors from `\e` to `\033`. This has wider support. `\e` is breaking on atleast some Macs

Improvements in e2e_tests

---

cmd/kpng/main.go
hack/kind.yaml
hack/kpng-deployment-ds-template.txt
hack/metrics/README.md
hack/metrics/deploy.sh
hack/metrics/nginx-values.yaml

Sets up prometheus server in kpng that can be scraped by prometheus master.
Sets up Grafana with prometheus as a data source.
Sets up a couple of default dashboards (for kube api server and nginx ingress controller).
Sets up an nginx ingress controller , so that Grafana can be accessed through ingress.
For some reason, the existing `--exposeMetrics` flag DOES NOT work => there seem to be problems with flag setup in the kpng cli.  Therefore, this adds a new function to set up the metrics server.
See new hack/metrics/README.md

expose metrics endpoint from within kpng

---

.github/workflows/vet-code.yml
hack/README.md
hack/update-gofmt.sh
hack/verify-gofmt.sh

Adds gofmt verification for pull requests and pushes to master branch

Adds gofmt verification

---

.github/workflows/backend-build.yml
.github/workflows/e2e_tests.yaml
.github/workflows/local-up-kpng.yaml
.github/workflows/unit_tests.yml
.github/workflows/vet-code.yml

Set go version on GitHub actions from `go.work` file.
[actions/setup-go](https://github.com/actions/setup-go) can retrieve the version of go used in the repository from the go.work file.
It reduces to lines that need rewriting when updating the go version.
- https://github.com/actions/setup-go/blob/30c39bfe0c7338d0d8e99486938f1066b2f92108/README.md#getting-go-version-from-the-gomod-file

Set go version on github actions from gowork file

---

backends/ebpf/README.md

Documentation
I had a little trouble compiling the eBPF program in Ubuntu:
``` 
$ make bytecode
...
bpf2go -cc clang -cflags -O2 -g -Wall -Werror -I./libbpf/include -I./libbpf/src bpf ./bpf/cgroup_connect4.c
In file included from /home/joao/Github/kpng/backends/ebpf/bpf/cgroup_connect4.c:3:
In file included from ./libbpf/include/uapi/linux/bpf.h:11:
/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
^~~~~~~~~~~~~
1 error generated.
Error: can't execute clang: exit status 1
ebpf.go:45: running "bpf2go": exit status 1
make: *** [Makefile:24: bytecode] Error 1
```
Looking for a fix, I found https://github.com/xdp-project/xdp-tools/issues/4, that points to https://github.com/xdp-project/xdp-tutorial/issues/44, which then proceeds to recommend the …

Add gcc-multilib as eBPF pre-requisite for Ubuntu

---

hack/test_skip_list.sh

Test improvement
Re-enable passing tests for `ipv4`-`ipvs` backend. A few tests were unnecessarily skipped, these can now be re-enabled
Relates to #445

ipv4-ipvs: enable passing tests

---

.github/workflows/e2e_tests.yaml

It fixes the eBPF dependency setup step in the e2e_test workflow.
As per @aroradaman [comment](https://github.com/kubernetes-sigs/kpng/pull/506#issuecomment-1561844221), it looks like the current pipeline is not able to find and download **gcc-multilib**. A simple `apt-get update` should theoretically solve this issue.

apt-get update before installing ebpf's backend dependencies

---

.github/workflows/e2e_tests.yaml
backends/ipvs/internal/ipvs/setup.go
backends/ipvs/internal/ipvs/util.go
backends/ipvs/setup.go

This PR complements #521.
This PR repeats #521 but also deletes installing `ipvsadm` in GH action since the `ipvs` module init happens in the code now.
Fixes #

Remove ipvsadm step

---

backends/ipvs/internal/ipvs/setup.go
backends/ipvs/internal/ipvs/util.go
backends/ipvs/setup.go

Bugfix
This PR loads [ipvs modules](https://github.com/kubernetes-sigs/kpng/blob/8a78a86a9e451a0b89fa749aa9746ff4ead4cab0/backends/ipvs/internal/ipvs/util.go#L100). 
When run locally with `ipvs` as a backend, `kpng` fail to start with error:
```
setup.go:36] unable to initialize ipvs managererror can't set sysctl net/ipv4/vs/conntrack to 1: open /proc/sys/net/ipv4/vs/conntrack: no such file or directory
```
The error occur because ipvs modules are not loaded, so there is no `/proc/sys/net/ipv4/vs` directory and the file [conntrack](https://github.com/kubernetes-sigs/kpng/blob/8a78a86a9e451a0b89fa749aa9746ff4ead4cab0/backends/ipvs/internal/ipvs/util.go#L67) cannot be created.
Fixes #
```sh
kind --version
kind version 0.20.0
```
Node is running `Ubuntu 22.04.2 LTS`:
```sh
cat …
```

Load ipvs modules before enabling conntrack

---

Dockerfile

Hopefully a bugfix.
This PR aligns `nftables` version in [kpng image](https://pkgs.alpinelinux.org/packages?name=nftables&branch=v3.16&repo=&arch=x86_64&maintainer=) and [os node image](https://packages.ubuntu.com/jammy/nftables).
Currently, when e2e tests run locally nft rules set up incorrectly due to the versions mismatch that results in `[invalid type]` in chains.
To reproduce 
1. start `kpng` without running tests via `./hack/test_e2e.sh -i ipv4 -b nft -d`
2. join a worker node, install `nftables` and check for `invalid type`:
```sh
kubectl node-shell kpng-e2e-ipv4-nft-worker
apt update && apt install -y nftables
nft list ruleset | grep invalid
```
`kpng` has nothing to do with that. One can reproduce it by ssh-ing to a kpng pod and applying nft rules:
```sh
vi nft.conf
table ip6 …
```

Downgrade kpng alpine image to align nftables with nodes OS.

---

Dockerfile
Makefile
cmd/kpng/main.go
cmd/kpng/version.go
hack/common.sh
hack/go-build
hack/kpng-local-up.sh
hack/test_e2e.sh
hack/tilt/deploy.sh

fixes #228 
The problem here likely stems from the fact that, currently, [there are too many ways to build and deploy KPNG](https://kubernetes.slack.com/archives/C02GA1RSCLR/p1673117536594379). None of them were passing the commit SHA to go build/install.
This PR:
- fixes the version command for `make tilt-up`, `make build`,  `kpng-local-up.sh`, and `test_e2e.sh`;
- makes all the tools above build `kpng` with the same command (`make image`);

fix kpng version command and standardize build command

---

api/go.mod
api/go.sum
api/localv1/endpoint.go
api/localv1/endpoint_test.go
backends/iptables/iptables.go
backends/nft/endpoint.go
backends/nft/svc-chain.go
client/plugins/conntrack/conntrack.go
client/plugins/conntrack/sink.go
server/jobs/kube2store/slice-event-handler.go
server/pkg/endpoints/node.go

Bugfix
First commit addresses a situation when an endpoint slice is not ready, but it was not set.
Second commit complements #520 (which can be closed in favor of this PR). The [port mapping](https://github.com/kubernetes-sigs/kpng/commit/6ec42e7b6ce414092d406ea1c9bc75bd849cea75#diff-797a7515d4f869cd70ff1e72a62fab4fd348ad3b509f9a815dbe45ffcbcb3638R34) should be done based on field precedence: 1. `port.Name`; 2. `port.TargetPortName`; 3. `port.TargetPort` (see the [adjusted test](https://github.com/kubernetes-sigs/kpng/commit/6ec42e7b6ce414092d406ea1c9bc75bd849cea75#diff-6979f344dc49b8ed56f05d876a188b024bbf09e14ebb5131323950208bae9a8fR54)).
Fixes #
Following tests pass:
- `EndpointSlice [It] should support a Service with multiple ports specified in multiple EndpointSlices`
- `EndpointSlice …

Fix epslices
